//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AddressTB()
        {
            this.BetaTBs = new HashSet<BetaTB>();
            this.DonorTBs = new HashSet<DonorTB>();
            this.RecieverTBs = new HashSet<RecieverTB>();
        }
    
        public int AddressID { get; set; }
        public string Street { get; set; }
        public string Town { get; set; }
        public string District { get; set; }
        public string Division { get; set; }
        public string PostCode { get; set; }
        public string PoliceStation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BetaTB> BetaTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonorTB> DonorTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecieverTB> RecieverTBs { get; set; }
    }
}
