//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetaTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BetaTB()
        {
            this.FamilyTBs = new HashSet<FamilyTB>();
            this.ReliefTBs = new HashSet<ReliefTB>();
        }
    
        public int BetaID { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string BetaPhoneNo { get; set; }
        public string BetaRelevent { get; set; }
    
        public virtual AddressTB AddressTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamilyTB> FamilyTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReliefTB> ReliefTBs { get; set; }
    }
}
