//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FamilyTB()
        {
            this.RecieverTBs = new HashSet<RecieverTB>();
        }
    
        public int FamilyID { get; set; }
        public string Name { get; set; }
        public string AuthTyp { get; set; }
        public string AuthNo { get; set; }
        public string Age { get; set; }
        public string Relation { get; set; }
        public Nullable<int> BetaID { get; set; }
    
        public virtual BetaTB BetaTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecieverTB> RecieverTBs { get; set; }
    }
}
