//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecieverTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecieverTB()
        {
            this.ReliefTBs = new HashSet<ReliefTB>();
        }
    
        public int RecieverID { get; set; }
        public string RecieverName { get; set; }
        public string AuthTyp { get; set; }
        public string NID { get; set; }
        public string BCID { get; set; }
        public string RecieverPhoneNo { get; set; }
        public Nullable<int> FamilyID { get; set; }
        public string Age { get; set; }
        public string FamilyMemberCount { get; set; }
        public Nullable<int> DonorID { get; set; }
        public Nullable<int> RecieveCount { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string RecieverJob { get; set; }
    
        public virtual AddressTB AddressTB { get; set; }
        public virtual FamilyTB FamilyTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReliefTB> ReliefTBs { get; set; }
    }
}
