//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonationTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonationTB()
        {
            this.DonorTBs = new HashSet<DonorTB>();
        }
    
        public int DonateID { get; set; }
        public string Amount { get; set; }
        public string Career { get; set; }
        public string DonateDate { get; set; }
        public Nullable<int> DonorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonorTB> DonorTBs { get; set; }
    }
}
