//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonorTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonorTB()
        {
            this.ReliefTBs = new HashSet<ReliefTB>();
        }
    
        public int DonorID { get; set; }
        public string DonorName { get; set; }
        public string Type { get; set; }
        public string Phone { get; set; }
        public string Message { get; set; }
        public string Visiblity { get; set; }
        public Nullable<int> DonateID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string Password { get; set; }
    
        public virtual AddressTB AddressTB { get; set; }
        public virtual DonationTB DonationTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReliefTB> ReliefTBs { get; set; }
    }
}
