//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CovidDatacontext : DbContext
    {
        public CovidDatacontext()
            : base("name=CovidDatacontext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressTB> AddressTBs { get; set; }
        public virtual DbSet<AdminTB> AdminTBs { get; set; }
        public virtual DbSet<BetaTB> BetaTBs { get; set; }
        public virtual DbSet<DonationTB> DonationTBs { get; set; }
        public virtual DbSet<DonorTB> DonorTBs { get; set; }
        public virtual DbSet<FamilyTB> FamilyTBs { get; set; }
        public virtual DbSet<RecieverTB> RecieverTBs { get; set; }
        public virtual DbSet<ReliefTB> ReliefTBs { get; set; }
    }
}
