//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReliefTB
    {
        public int DonationID { get; set; }
        public Nullable<int> RecieverID { get; set; }
        public Nullable<int> DonorID { get; set; }
        public string DonationDate { get; set; }
        public string DonationStatus { get; set; }
        public Nullable<int> BetaID { get; set; }
    
        public virtual BetaTB BetaTB { get; set; }
        public virtual DonorTB DonorTB { get; set; }
        public virtual RecieverTB RecieverTB { get; set; }
    }
}
